baseURL = "https://blog.breno5g.dev/"
title = "Blog | Breno5G"
theme = "hugo-bearcub"

defaultContentLanguage = "pt"
defaultContentLanguageInSubdir = false
languageCode = "pt-BR"

copyright = "Breno Santos"

enableRobotsTXT = true
hideUntranslated = false

[markup]
  [markup.highlight]
    lineNos = true
    lineNumbersInTable = false
    noClasses = false

[params]
  description = "Um diÃ¡rio pessoal sobre programaÃ§Ã£o, engenharia de software e ideias em andamento. Um espaÃ§o simples para escrever devagar, organizar pensamentos e registrar o processo."
  dateFormat = "2006-01-02"
  themeStyle = "original"
  generateSocialCard = true

  [params.social]
    twitter = "breno5g"
    github = "breno5g"

  [params.author]
    name = "Breno Santos"

[languages]

  [languages.en]
    languageName = "en-US ðŸ‡ºðŸ‡¸"
    LanguageCode = "en-US"
    weight = 1
    contentDir = "content.en"
    title = "Blog | Breno5G"

    [languages.en.params]
      madeWith = "Made with [Bear Cub](https://github.com/clente/hugo-bearcub)"
      description = "A personal diary about software, programming, and ideas in progress."

  [languages.pt]
    languageName = "pt-BR ðŸ‡§ðŸ‡·"
    LanguageCode = "pt-BR"
    weight = 2
    contentDir = "content.pt"
    title = "Blog | Breno5G"

    [languages.pt.params]
      madeWith = "Feito com [Bear Cub](https://github.com/clente/hugo-bearcub)"
      description = "Um diÃ¡rio pessoal sobre programaÃ§Ã£o, engenharia de software e ideias em andamento."
